Update compatibility matrix
pytorch/audio pull request #1084
Opened 2020-12-10 16:36 UTC by vincentqb

Add 0.7.2 release and specify 3.8 and 3.9 requirements

2020-12-11 17:37 UTC, cpuhrsch approved these changes

2020-12-11 17:39 UTC, cpuhrsch requested changes
Let's land this one we have Python3.9 tests on circleci running

2021-02-19 19:25 UTC, vincentqb commented
cc #1242

2021-02-19 19:36 UTC, vincentqb commented
Updated with 0.8. Let's merge this once the release is done.

2021-03-09 17:35 UTC, cpuhrsch approved these changes

2021-03-09 17:35 UTC, merged