Fixed Code Quality Issues
pytorch/audio pull request #1351
Opened 2021-03-04 06:12 UTC by ankitdobhal

## Description

Hi 👋 I ran the [DeepSource](https://deepsource.io/) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/ankitdobhal/audio/issues). This PR fixes a few of them.

## Summary of Fixes

-  Fixed Object Inheritance
-  Consider merging these comparisons with 'in'
-  Fixed collapsible if statement
-  Added .deepsource.toml to fix bug risk

## Type of change

- [✔] Antipattern
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [✔] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2021-03-04 15:16 UTC, mthrok commented
Hi @ankitdobhal 

Thanks for opening the PR. The changes to code itself looks good, but we cannot add the configuration file at the moment without an approval from PyTorch. If you remove the toml file, we can merge this PR. and if you want to pursue adding the toml file, please first open an issue in https://github.com/pytorch/pytorch/issues/new/choose and get an approval.

2021-03-05 04:07 UTC, ankitdobhal commented
> Hi @ankitdobhal
> 
> Thanks for opening the PR. The changes to code itself looks good, but we cannot add the configuration file at the moment without an approval from PyTorch. If you remove the toml file, we can merge this PR. and if you want to pursue adding the toml file, please first open an issue in https://github.com/pytorch/pytorch/issues/new/choose and get an approval.

Hi @mthrok.
Thanks for response . As per your suggestion I have opened a new Issue about   Potential Bug Risks and Anti-Patterns.
#1358

2021-03-05 04:16 UTC, mthrok commented
> > Hi @ankitdobhal
> > Thanks for opening the PR. The changes to code itself looks good, but we cannot add the configuration file at the moment without an approval from PyTorch. If you remove the toml file, we can merge this PR. and if you want to pursue adding the toml file, please first open an issue in https://github.com/pytorch/pytorch/issues/new/choose and get an approval.
> 
> Hi @mthrok.
> Thanks for response . As per your suggestion I have opened a new Issue about Potential Bug Risks and Anti-Patterns.
> #1358

Please open it in pytorch/pytorch, not in pytorch/audio.

2021-03-05 04:26 UTC, ankitdobhal commented
> > > Hi @ankitdobhal
> > > Thanks for opening the PR. The changes to code itself looks good, but we cannot add the configuration file at the moment without an approval from PyTorch. If you remove the toml file, we can merge this PR. and if you want to pursue adding the toml file, please first open an issue in https://github.com/pytorch/pytorch/issues/new/choose and get an approval.
> > 
> > 
> > Hi @mthrok.
> > Thanks for response . As per your suggestion I have opened a new Issue about Potential Bug Risks and Anti-Patterns.
> > #1358
> 
> Please open it in pytorch/pytorch, not in pytorch/audio.

@mthrok thanks , opened issue in official pytorch repo.
https://github.com/pytorch/pytorch/issues/53338

2021-03-11 12:06 UTC, ankitdobhal commented
> Hi @ankitdobhal
> 
> Thanks for opening the PR. The changes to code itself looks good, but we cannot add the configuration file at the moment without an approval from PyTorch. If you remove the toml file, we can merge this PR. and if you want to pursue adding the toml file, please first open an issue in https://github.com/pytorch/pytorch/issues/new/choose and get an approval.

@mthrok I have removed the .toml file.
Now kindly merge the fixes .
Thanks

2021-03-12 04:52 UTC, mthrok requested changes
Please address the comments.

2021-03-12 04:52 UTC, mthrok commented on examples/interactive_asr/vad.py
> +class VoiceActivityDetection():
Can you remove `()`?

2021-03-12 04:52 UTC, mthrok commented on examples/interactive_asr/vad.py
> +class MicrophoneStream():
Can you remove `()`?

2021-03-12 04:52 UTC, mthrok commented on test/torchaudio_unittest/compliance/generate_fbank_data.py
> +    sound, sample_rate = torchaudio.load_wav(sound_path)
`load_wav` has been removed and this no longer works. Please revert the change.

2021-03-12 07:16 UTC, closed without merging

2021-03-12 07:44 UTC, ankitdobhal commented
@mthrok I have created new clean PR .
#1386  now review and merge the fixes.