Deprecate data utils
pytorch/audio pull request #1945
Opened 2021-10-29 04:37 UTC by harishsdev

Deprecate data utils

PR for https://github.com/pytorch/audio/issues/1883

2021-11-01 17:49 UTC, mthrok requested changes
Hi @harishsdev 

Thanks for working on this. Please refer to my comments.

2021-11-01 17:49 UTC, mthrok commented on torchaudio/datasets/cmuarctic.py
> +                    download_url_to_file(url, root, hash_prefix=checksum)
`download_url_to_file` can only handle SHA256 hash, therefore the MD5 sum cannot be passed to the function. 
Either the checksum needs to be updated to SHA256 or validation has to be performed separately after the download.

2021-11-01 17:49 UTC, mthrok commented on torchaudio/datasets/utils.py
> -def download_url(url: str,
We cannot delete the function until the next release. The `deprecated` decorator has to be put on this `download_url`.

2021-11-01 17:49 UTC, mthrok commented on torchaudio/datasets/yesno.py
> +)
This decorator should be added on the implementation of `download_url_to_file`.
Also, `version` has to be keyword argument, not string.

2021-11-14 19:36 UTC, krishnakalyan3 commented
@harishsdev please let me know if you will continue to work on this issue. Else I would want to take a stab at this.

2021-12-14 08:33 UTC, harishsdev commented
@krishnakalyan3 please continue,im no more working on this isssue

2021-12-18 05:15 UTC, closed without merging