Torchaudio load libary path fix for windows python 3.8
pytorch/audio pull request #2735
Opened 2022-10-04 21:36 UTC by atalman

Torchaudio load libary path fix for windows python 3.8

2022-10-04 21:49 UTC, malfet commented on torchaudio/_extension.py
> +            warn("LoadLibraryExW is missing in kernel32.dll")
Can we mention that this is a copy-n-paste from respective TorchVision file? And perhaps just move it to core PyTorch, as torchtext can run into this one as well at some point

2022-10-05 00:23 UTC, mthrok requested changes
Please change the name of the module `internally_replaced_utils.py`.
In torchaudio, we make efforts to make the code not diverge between OSS and fbcode, and we rather want to show up in the logic, not in the module name.

Use the pattern;

```
try:
    from .fb.foo_util import foo
except ImportError:
    from .foo_util import foo
```

2022-10-05 15:49 UTC, weiwangmeta commented on torchaudio/_extension.py
> +    if os.name == "nt" and sys.version_info >= (3, 8):
Is >= necessary or == would be sufficient? I thought we do not have this issue for python 3.9+?

2022-10-05 16:10 UTC, weiwangmeta approved these changes
Thanks for the great fix!

2022-10-05 21:17 UTC, mthrok requested changes

2022-10-05 21:17 UTC, mthrok commented on torchaudio/_extension.py
> +                print(f" Calling add_dll_directory with: {path}")
Print is not controllable, please use logging.

2022-10-06 16:13 UTC, closed without merging